--- #YAML:1.0
name: Test-DistManifest
version: 1.001004
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: |-
  Tests that your MANIFEST matches the distribution as it
  exists, excluding those in your MANIFEST.SKIP
license: perl
resources:
  Ratings: http://cpanratings.perl.org/d/Test-DistManifest
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-DistManifest
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Test-DistManifest
requires:
  Carp: 1.04
  Cwd: 0
  File::Find: 0
  File::Spec: 0
  File::Spec::Unix: 0
  Module::Manifest: 0.07
  Test::Builder: 0.86
  Test::More: 0.62
  perl: 5.006
  strict: 0
  version: 0
  warnings: 0
build_requires:
  Test::Builder::Tester: 0
  Test::NoWarnings: 0.084
recommends:
  Test::Kwalitee: 1.01
  Test::Perl::Critic: 1.01
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
  Test::Signature: 1.10
  Test::YAML::Meta: 0.11
  Test::Portability::Files: 0.05
  Test::MinimumVersion: 0.008
  Test::Prereq::Build: 1.036
  Test::Portability::Files: 0.05
  Test::MinimumVersion: 0.008
dynamic_config: 0
provides:
  Test::DistManifest:
    file: lib/Test/DistManifest.pm
    version: 1.001004
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
